## Numpy Arithmatic:

In [1]:
import numpy as np

array = np.arange(11)

In [2]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
array + array # adds corresponding entries of the arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
array - array  # subtracts corresponding entries of the arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
array * array  # multiply corresponding entries of the arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
array / array # divids the corresponding entreis of the arrays

C:\Users\umair\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# above warning is on dividing 0 with 0, which results and undefined form

In [10]:
# similarly

1 / array

C:\Users\umair\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
array * 3 # if multiplied by some scaler it results just like scaler division

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
array ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
array ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### Universal Array Functions:

### sqrt:

In [21]:
square_root = np.sqrt(array)

In [23]:
square_root # reports back the square roots of each item

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [24]:
random_array = np.random.randint(1,100,20)

In [25]:
random_array

array([12, 86, 17, 36, 35, 79, 24, 88, 28, 67, 20, 28, 35, 80, 52, 81, 76,
       21, 92, 13])

In [27]:
random_array.sort()

In [28]:
random_array

array([12, 13, 17, 20, 21, 24, 28, 28, 35, 35, 36, 52, 67, 76, 79, 80, 81,
       86, 88, 92])

In [29]:
sqrt_random_array = np.sqrt(random_array)

In [30]:
sqrt_random_array

array([3.46410162, 3.60555128, 4.12310563, 4.47213595, 4.58257569,
       4.89897949, 5.29150262, 5.29150262, 5.91607978, 5.91607978,
       6.        , 7.21110255, 8.18535277, 8.71779789, 8.88819442,
       8.94427191, 9.        , 9.2736185 , 9.38083152, 9.59166305])

In [31]:
integer = np.random.randint(100)

In [32]:
int_sqrt = np.sqrt(integer)

In [34]:
integer

1

In [36]:
int_sqrt  # reports back the square root of generated integer

1.0

In [38]:
## built-in exponential function

np.exp(array) # reports back array with each entry corresponds to the power of 'e' i.e 2.71

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [39]:
rand_int = np.random.randint(10)

In [40]:
np.exp(rand_int)

1096.6331584284585

In [41]:
rand_array = np.random.randn(10)

In [42]:
rand_array

array([ 0.37924322, -0.29911067, -3.44983417, -0.88571967, -0.95187042,
        0.86707601,  0.27361534, -0.16455762,  0.90487026,  0.30302495])

In [43]:
np.exp(rand_array)

array([1.46117838, 0.74147735, 0.0317509 , 0.41241726, 0.38601833,
       2.37994175, 1.314709  , 0.84826888, 2.47161123, 1.35394824])

In [44]:
rand_uniform_array = np.random.rand(10)

In [46]:
rand_uniform_array

array([0.35422937, 0.4866276 , 0.02342977, 0.43370611, 0.58172403,
       0.75313924, 0.66645522, 0.68343665, 0.86469471, 0.5238502 ])

In [47]:
np.exp(rand_uniform_array)

array([1.42508202, 1.62682067, 1.0237064 , 1.54296534, 1.78912027,
       2.12365622, 1.94732224, 1.98067292, 2.37428114, 1.68851627])

In [49]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
array.max()

10

In [51]:
array.argmax()

10

In [52]:
array.min()

0

In [53]:
array.argmin()

0

In [54]:
np.max(array) # reports back the same results as array.max

10

In [55]:
np.min(array)

0

In [56]:
np.argmax(array)

10

In [57]:
np.argmin(array)

0

## sine, cosine and log functions:

In [58]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
sine_of_nums = np.sin(array)

In [61]:
sine_of_nums # reports back sine angle of every corresponding item

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [64]:
cosine_of_nums = np.cos(array)

In [65]:
cosine_of_nums # reports back the cosines of each corresponding array entry

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [68]:
logs = np.log(array)

C:\Users\umair\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [66]:
num = 90
np.sin(num)

0.8939966636005579

In [67]:
num = 0
np.cos(num)

1.0

In [69]:
num = 1
np.log(num)

0.0