## Numpy Indexing And Selections:

In [1]:
import numpy as np

In [3]:
# creating a simple array

array = np.arange(10)

## Bracket Indexing And Selections:

In [4]:
# getting the value off of an index

array[2]

2

In [5]:
array[3]

3

In [6]:
array[8]

8

In [7]:
array[7]

7

In [8]:
arr = np.random.rand(10)

In [10]:
arr

array([0.91610988, 0.47512732, 0.91372907, 0.35296106, 0.83468948,
       0.61679139, 0.43125471, 0.48560428, 0.77629734, 0.542202  ])

In [11]:
arr[3]

0.35296106052486775

In [12]:
arr[5]

0.6167913941040439

In [21]:
array2 = np.random.randn(10)

In [22]:
array2

array([ 1.30294797,  1.55167883,  0.27112018,  0.97614072,  1.26832102,
        1.63909713,  0.25293074, -0.78899824, -0.6012332 ,  0.71035097])

In [23]:
array2[2]

0.2711201767738288

In [24]:
# slicing an array and selecting values from required indexes

array3 = np.random.randint(1,100,10)

In [25]:
array3

array([57, 70, 86, 39, 34, 94, 68, 36, 68, 13])

In [26]:
array3.sort()

In [27]:
array3

array([13, 34, 36, 39, 57, 68, 68, 70, 86, 94])

In [28]:
array3[0:5]

array([13, 34, 36, 39, 57])

In [29]:
array3[-1:-3]

array([], dtype=int32)

In [35]:
array3[-1]

94

## Broadcasting:


In [49]:
my_array = np.arange(20)

In [50]:
my_array[:4] = 100

In [51]:
my_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [52]:
my_array[:] = 99

In [53]:
my_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99])

In [54]:
my_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99])

In [58]:
copy = my_array.copy()

In [59]:
copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99])

## 2d Arrays:

In [60]:
arr_2d = np.array([[1,2],[3,4]])

In [61]:
arr_2d

array([[1, 2],
       [3, 4]])

In [62]:
arr_2d_2 = np.array([[2,3,3],[4,8,7]])

In [63]:
arr_2d_2

array([[2, 3, 3],
       [4, 8, 7]])

In [64]:
arr_2d_2.shape

(2, 3)

## Indexing 2d Arrays:

In [65]:
array_2d = np.array([[2.0,3.0],[4.0,7.0]])

In [66]:
array_2d

array([[2., 3.],
       [4., 7.]])

In [68]:
array_2d[1] # grabs the row at index one of the 2-dimensions array

array([4., 7.])

In [69]:
array_2d[0] # grabs the row at index two of the 2-dimensions array

array([2., 3.])

In [75]:
array = np.random.randint(1,100,25)

In [76]:
array

array([31, 47,  2, 84, 54,  5, 74, 71, 97, 38, 46,  7, 45, 93,  7, 99, 34,
        2, 90, 48, 91,  5, 25, 74, 27])

In [77]:
array = array.reshape(5,5)

In [78]:
array

array([[31, 47,  2, 84, 54],
       [ 5, 74, 71, 97, 38],
       [46,  7, 45, 93,  7],
       [99, 34,  2, 90, 48],
       [91,  5, 25, 74, 27]])

In [79]:
array[2] # reports back the row at index no. 2

array([46,  7, 45, 93,  7])

In [81]:
# Formate is array[row][column]
# so for value at the 3rd index row and 2nd index column we have..

array[3][2]

2

In [83]:
array[:] # reports back the whole array

array([[31, 47,  2, 84, 54],
       [ 5, 74, 71, 97, 38],
       [46,  7, 45, 93,  7],
       [99, 34,  2, 90, 48],
       [91,  5, 25, 74, 27]])

In [84]:
array[2] # reports back the row at index 2

array([46,  7, 45, 93,  7])

In [85]:
array[0][1]

47

## Slicing Of 2d Arrays:

In [87]:
array[:2] # reports back rows at index 0 and index 1

array([[31, 47,  2, 84, 54],
       [ 5, 74, 71, 97, 38]])

In [90]:
array[1:2] # reports back the array at index location 1

array([[ 5, 74, 71, 97, 38]])

In [92]:
array

array([[31, 47,  2, 84, 54],
       [ 5, 74, 71, 97, 38],
       [46,  7, 45, 93,  7],
       [99, 34,  2, 90, 48],
       [91,  5, 25, 74, 27]])

In [95]:
array[:3,:2] # reports back rows from index 0-2 and columns from index 0-1

array([[31, 47],
       [ 5, 74],
       [46,  7]])

In [97]:
array[:3,:3] # reports back rows from index 0-2 and columns from index 0-2

array([[31, 47,  2],
       [ 5, 74, 71],
       [46,  7, 45]])

In [99]:
array[2,:] # report back the row from bottom index position 2

array([46,  7, 45, 93,  7])

In [101]:
array[:,3] # reports back column from index 3

array([84, 97, 93, 90, 74])

In [102]:
array

array([[31, 47,  2, 84, 54],
       [ 5, 74, 71, 97, 38],
       [46,  7, 45, 93,  7],
       [99, 34,  2, 90, 48],
       [91,  5, 25, 74, 27]])

In [104]:
array[1:4,1:4] # reports back the rows from index 1-4 and columns from index 1-4

array([[74, 71, 97],
       [ 7, 45, 93],
       [34,  2, 90]])

In [105]:
array[:,4]

array([54, 38,  7, 48, 27])

In [111]:
array[4] # reports back the row at index no. 4

array([91,  5, 25, 74, 27])

In [113]:
array[:,2] # reports back the column at index no. 2

array([ 2, 71, 45,  2, 25])

In [114]:
zeros = np.zeros((10,10))

In [115]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
arr_length = zeros.shape[1]

In [119]:
arr_length

10

In [120]:
for i in range(arr_length):
    zeros[i] = i

In [121]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

## Selections with comparison operators:

In [122]:
array = np.arange(10)

In [123]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
array > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [125]:
array < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [126]:
array <= 5

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [127]:
bool_array = array < 5

In [129]:
array[bool_array]

array([0, 1, 2, 3, 4])

In [130]:
bool_arr = array > 5

array[bool_arr]

array([6, 7, 8, 9])

In [132]:
comp_array = array <= 4

In [133]:
array[comp_array]

array([0, 1, 2, 3, 4])

In [135]:
x = 4

array[array > x]

array([5, 6, 7, 8, 9])

In [136]:
y = 8

array[array < y]

array([0, 1, 2, 3, 4, 5, 6, 7])