### Numpy Operation:

In [1]:
mylist = [1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
# to convert python list to numpy array we can do it directly by

myarray = np.array(mylist)

In [5]:
# now lets see the difference 
print(type(mylist))
print(type(myarray))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
# similarly, we can convert list of lists to numpy arrays as well

lists = [[1,2,3],[2,3,4],[5,6,7]]
arrays = np.array(lists)

In [7]:
lists

[[1, 2, 3], [2, 3, 4], [5, 6, 7]]

In [8]:
arrays

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [9]:
print(type(lists))
print(type(arrays))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
mymatrix = [[2,3,3],[4,7,7],[8,8,9]]

In [11]:
mymatrix

[[2, 3, 3], [4, 7, 7], [8, 8, 9]]

In [12]:
type(mymatrix)

list

In [13]:
new_matrix = np.array(mymatrix)

In [14]:
new_matrix

array([[2, 3, 3],
       [4, 7, 7],
       [8, 8, 9]])

In [15]:
type(new_matrix)

numpy.ndarray

### Built-In Methods:

In [16]:
# there are variety of methods to generate numpy arrays

array = np.arange(0,10)

In [17]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
type(array)

numpy.ndarray

In [19]:
# we can also add some step size in our array vector

array1 = np.arange(0,11,2)

In [20]:
array1

array([ 0,  2,  4,  6,  8, 10])

In [21]:
# generating arrays of zeros and ones

zeros = np.zeros(3)

In [27]:
zeros

array([0., 0., 0.])

In [28]:
ones = np.ones(5)

In [29]:
ones

array([1., 1., 1., 1., 1.])

In [32]:
zeros = np.zeros((4,4))
ones = np.ones((5,5))

In [35]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
new_ones = np.ones((2,3))

In [38]:
new_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
new_zeros = np.zeros((3,2))

In [40]:
new_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Linspace:

### Returns evenly spaced number over  a specified interval

In [45]:
evenly_spaced_nums = np.linspace(0,9,10)

In [46]:
evenly_spaced_nums

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
evenly_spaced_nums = np.linspace(1,10,100)

In [48]:
evenly_spaced_nums

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

## Eye:

### Creates an identity matrix

In [54]:
eye = np.eye(3)

In [57]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
eye_1 = np.eye(5)

In [59]:
eye_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random:

In [62]:
# this rand function will report back 'n' numbers uniformly distributed from [0,1)

random_array = np.random.rand(10)

In [61]:
random_array

array([0.41994952, 0.78181432, 0.01186946, 0.87796111, 0.20090346,
       0.44377303, 0.86750204, 0.77554432, 0.61976437, 0.35610569])

In [64]:
random_array = np.random.rand(50)

In [65]:
random_array

array([0.09892526, 0.08101329, 0.63621131, 0.31419545, 0.75653008,
       0.25532847, 0.30068735, 0.31924967, 0.72318474, 0.92022741,
       0.76605557, 0.60579263, 0.44687762, 0.03821947, 0.6424155 ,
       0.10775314, 0.31924878, 0.50475614, 0.57228973, 0.34313753,
       0.681637  , 0.8819074 , 0.98227466, 0.246146  , 0.73271021,
       0.10354132, 0.79544481, 0.04316408, 0.47144994, 0.68029034,
       0.02565428, 0.8956969 , 0.61293001, 0.48832644, 0.63404791,
       0.29084783, 0.20982167, 0.44330251, 0.39337353, 0.85002289,
       0.77410923, 0.72160824, 0.56420344, 0.49516997, 0.78679769,
       0.92639704, 0.03417865, 0.63254936, 0.5758633 , 0.88313034])

In [66]:
random_array

array([0.09892526, 0.08101329, 0.63621131, 0.31419545, 0.75653008,
       0.25532847, 0.30068735, 0.31924967, 0.72318474, 0.92022741,
       0.76605557, 0.60579263, 0.44687762, 0.03821947, 0.6424155 ,
       0.10775314, 0.31924878, 0.50475614, 0.57228973, 0.34313753,
       0.681637  , 0.8819074 , 0.98227466, 0.246146  , 0.73271021,
       0.10354132, 0.79544481, 0.04316408, 0.47144994, 0.68029034,
       0.02565428, 0.8956969 , 0.61293001, 0.48832644, 0.63404791,
       0.29084783, 0.20982167, 0.44330251, 0.39337353, 0.85002289,
       0.77410923, 0.72160824, 0.56420344, 0.49516997, 0.78679769,
       0.92639704, 0.03417865, 0.63254936, 0.5758633 , 0.88313034])

In [67]:
random_array_1 = np.random.rand(10)

In [68]:
random_array_1

array([0.35012805, 0.61244857, 0.26485955, 0.62479444, 0.95655159,
       0.42644551, 0.2181782 , 0.25860322, 0.74667314, 0.83651487])

In [70]:
random_matrix = np.random.rand(5,5)

In [71]:
random_matrix

array([[0.82551   , 0.66441675, 0.07087526, 0.53272472, 0.79790845],
       [0.89450684, 0.01886068, 0.10735699, 0.96615545, 0.93424457],
       [0.88274099, 0.39646493, 0.41919912, 0.10921732, 0.3252103 ],
       [0.91391311, 0.65334984, 0.946197  , 0.08428831, 0.42890542],
       [0.9047979 , 0.4917818 , 0.8670554 , 0.63858602, 0.83773506]])

In [73]:
random_matrix_1 = np.random.rand(10,10)

random_matrix_1

array([[0.98968544, 0.810486  , 0.65879014, 0.96442172, 0.84886606,
        0.41979569, 0.40287797, 0.05249638, 0.6370717 , 0.52797219],
       [0.73925849, 0.1740975 , 0.34923192, 0.75106704, 0.50839366,
        0.54580202, 0.41622166, 0.94396688, 0.47535859, 0.398939  ],
       [0.36026025, 0.97842555, 0.91779468, 0.5459723 , 0.08184342,
        0.45574886, 0.0308595 , 0.28994241, 0.93682928, 0.15414762],
       [0.49463964, 0.04461382, 0.16164553, 0.62381828, 0.50710413,
        0.70527759, 0.06187726, 0.85742179, 0.30072983, 0.9874086 ],
       [0.51433693, 0.90593026, 0.19925629, 0.96647867, 0.89941552,
        0.274524  , 0.60188001, 0.94815867, 0.83564639, 0.18922251],
       [0.42930141, 0.3003026 , 0.90853289, 0.96120444, 0.2057031 ,
        0.57338382, 0.19816672, 0.77659435, 0.54918301, 0.98377867],
       [0.36965354, 0.11933139, 0.12555172, 0.72430092, 0.40343933,
        0.78119028, 0.29831378, 0.52896164, 0.231948  , 0.72852942],
       [0.65586175, 0.62177052, 0.9686444

In [75]:
random_matrix_1.shape

(10, 10)

## randn:

#### randn differs from rand function is such a way that it reports back values of vector with standart normal distribution, having mean = 0 and standart deviation = 1. But, normal rand function is uniformly distributed having equal interval length for all values

In [78]:
random_vec = np.random.randn(3)

In [79]:
random_vec

array([-0.5135593 ,  0.62220934, -1.99929733])

In [80]:
random_matrix = np.random.randn(4,4)

In [81]:
random_matrix

array([[ 0.59129667, -0.72200776,  1.25784638,  0.66665627],
       [-1.10033661,  2.02950907, -0.51299491,  0.47268705],
       [-0.38955485, -1.23692556,  0.15616137, -1.31134861],
       [-0.9496604 , -1.0628157 , -1.29474538,  0.49203246]])

In [82]:
random_vec_2 = np.random.randn(5)

In [83]:
random_vec_2

array([-0.3312913 ,  0.85989135,  1.22465913,  0.33459038, -0.87198877])

In [84]:
random_mat_2 = np.random.randn(5,5)

In [85]:
random_mat_2

array([[ 0.23155315, -1.2176536 , -0.52737222, -0.78093272,  0.02601163],
       [-1.6282568 , -1.34278118, -1.25149524, -0.69802541, -0.86237503],
       [ 0.51052134,  0.93371731, -0.70183171,  1.58850427, -0.66576514],
       [ 0.37429585,  0.34111909, -1.59266521,  0.16323627, -0.31671332],
       [ 0.59225541, -0.32177723, -0.06269958,  1.58152319, -0.30799897]])

## randint:

### reports back the random integers in specified interval

In [92]:
random_int = np.random.randint(10)

In [93]:
random_int

7

In [94]:
# the argument values represent the start, end, and total numbers we want to produce

random_vector = np.random.randint(1,100,10)

In [95]:
random_vector

array([81, 25,  4, 15, 73, 28, 67, 82, 59, 63])

In [110]:
# lets try them all out once more

random_vector = np.random.rand(5)
random_vector_2 = np.random.randn(5)
random_matrix_uniform = np.random.rand(5,5)
random_matrix_normal = np.random.randn(5,5)
random_int = np.random.randint(5)
random_specified_integers = np.random.randint(1,100,20)

In [101]:
random_vector # uniform distribution

array([0.10723076, 0.87923622, 0.58222009, 0.4427282 , 0.47108395])

In [102]:
random_vector_2 # standart normal distribution

array([ 1.3523986 , -0.53721703,  0.43412944,  0.15597967,  0.19432235])

In [105]:
random_matrix_uniform # uniformly distributed

array([[0.77544226, 0.39737516, 0.86930999, 0.4600291 , 0.07821826],
       [0.05342518, 0.81947767, 0.91781692, 0.46891646, 0.69135082],
       [0.4107876 , 0.50568163, 0.24661961, 0.73720637, 0.49732297],
       [0.6310149 , 0.71409049, 0.25661162, 0.84731066, 0.58936304],
       [0.81550148, 0.47344164, 0.84784469, 0.43026425, 0.75200354]])

In [106]:
random_matrix_normal # normally distributed

array([[-0.71627896, -0.10100196,  0.20953091, -1.48624926, -0.26472724],
       [ 1.45320367,  0.89989964,  0.82003988, -0.52025558,  0.9287696 ],
       [-0.08186026, -1.88354727, -0.48105726, -0.21651768,  0.11191853],
       [-0.21415736, -0.01105254,  1.4318151 ,  0.56686919, -1.70118205],
       [ 0.00541025, -0.69873419,  0.10601398, -0.54311945,  1.30999303]])

In [108]:
random_int # reports back random integer in specified interval i.e 5

3

In [112]:
random_specified_integers # reports back specified number of integers in specified interval i.e 20, 100

array([11, 50, 44, 90, 91, 30, 16, 17, 44, 41, 47, 72, 74, 57, 25, 61, 20,
       65, 25, 22])

just for the confirmation :)

len(random_specified_integers)

## Array Attributes:

In [116]:
array = np.arange(20)
random_array = np.random.randint(1,100,25)

In [117]:
array # reports back a sequenced vector in specified range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
random_array # reports back a random vector of specified numbers i.e 25, in specified interval i.e 1-100

array([45, 27, 46, 55, 66, 67, 79, 92, 56, 79, 96, 81, 99, 48, 51, 10, 67,
       10, 83, 39, 73, 34,  4, 80, 20])

In [119]:
len(random_array)

25

In [120]:
len(array)

20

In [129]:
random_vector = np.random.randint(1,100,25)

In [130]:
random_vector

array([36, 18, 64, 12, 90, 76, 41, 69, 13, 51, 50, 55, 70, 95, 10, 74, 14,
       55, 99, 73, 69, 81, 12, 90, 32])

In [131]:
random_vector.shape

(25,)

In [132]:
random_vector.reshape(5,5)

array([[36, 18, 64, 12, 90],
       [76, 41, 69, 13, 51],
       [50, 55, 70, 95, 10],
       [74, 14, 55, 99, 73],
       [69, 81, 12, 90, 32]])

In [133]:
random_matrix = np.random.rand(5,5)

In [134]:
random_matrix

array([[0.90190265, 0.10688985, 0.12797508, 0.12792623, 0.67807603],
       [0.03482933, 0.57132176, 0.29586046, 0.04807616, 0.57396115],
       [0.62905893, 0.67758307, 0.99272289, 0.13598556, 0.11471327],
       [0.61173715, 0.20120997, 0.3323042 , 0.38959751, 0.05656353],
       [0.78082737, 0.9275926 , 0.31456518, 0.04028569, 0.69384448]])

### max, min, argmax, argmin:

In [136]:
RandomArray = np.random.randint(0,100,30)

In [137]:
RandomArray

array([93, 92, 64, 42, 19, 53, 85, 11, 83, 37, 45, 87, 81, 13, 26, 92, 93,
        0, 74, 67, 96, 23, 19, 95, 30, 84, 48, 37,  9, 51])

In [139]:
len(RandomArray)

30

In [145]:
np.max(RandomArray)  # reports back the maximum value from numpy array

96

In [146]:
np.argmax(RandomArray) # reports back the index of that maximum value

20

In [147]:
np.min(RandomArray)  # reports back the minimum value from the numpy arrary

0

In [148]:
np.argmin(RandomArray)  # reports back the index of that minimun value

17

## Shape:

### shape is an attribute that reports back the shape of dimension of specific matrix

In [149]:
array = np.arange(10)

In [151]:
array.shape  # represents our matrix has 10 rows and no column

(10,)

In [152]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

matrix.shape

In [159]:
array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## dtype:

In [161]:
array.dtype # reports back the data type of integer i.e 32 or 64

dtype('int32')

In [162]:
array = np.arange(10)

In [163]:
array.shape

(10,)

In [164]:
array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [165]:
array.shape

(10,)

In [179]:
array.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [180]:
a.dtype

dtype('int32')