## Pandas Series:

#### Pandas series data type are the first building block of Pandas library. A series is very similar to NumPy array. What differences a series from a NumPy array is that, a Series can have a axis labels, meaning it can be indexed by labels instead of just location number. It also does not need to hold a numeric data, it can hold any Arbitrary Python object.

In [59]:
import numpy as np

In [60]:
import pandas as pd

In [61]:
# creating a series
# you can convert a python list, numpy array, or python dictionary to a pandas series

labels = ['a', 'b', 'c', 'd']
mylist = [10,20,30,40]
array = np.array(mylist)
dic = {'a':10, 'b':20, 'c':30, 'd':40}

In [62]:
# converting all the above data structures to pandas series
# we are gonna do the following

pd.Series(data = labels)

0    a
1    b
2    c
3    d
dtype: object

In [63]:
pd.Series(data = mylist)

0    10
1    20
2    30
3    40
dtype: int64

In [64]:
pd.Series(data = array)

0    10
1    20
2    30
3    40
dtype: int32

In [65]:
pd.Series(data = dic)

a    10
b    20
c    30
d    40
dtype: int64

In [66]:
labels = ['a', 'b', 'c', 'd']
mylist = [10,20,30,40]
array = np.array(mylist)
dic = {'a':10, 'b':20, 'c':30, 'd':40}

In [67]:
pd.Series(data = mylist, index = labels)

a    10
b    20
c    30
d    40
dtype: int64

In [68]:
pd.Series(data = array, index = labels)

a    10
b    20
c    30
d    40
dtype: int32

In [69]:
pd.Series(data = labels, index = mylist)

10    a
20    b
30    c
40    d
dtype: object

In [73]:
pd.Series(data = dic, index = 'l m n o'.split())

l   NaN
m   NaN
n   NaN
o   NaN
dtype: float64

In [74]:
pd.Series(data = dic)

a    10
b    20
c    30
d    40
dtype: int64

In [75]:
array

array([10, 20, 30, 40])

In [76]:
mylist = list(array)

In [78]:
mylist

[10, 20, 30, 40]

In [79]:
array = np.array(mylist)

In [80]:
array

array([10, 20, 30, 40])

In [81]:
a = pd.Series(data = array)

In [82]:
a

0    10
1    20
2    30
3    40
dtype: int32

In [83]:
array1 = np.array(a)

In [84]:
array1

array([10, 20, 30, 40])

In [85]:
# above were some of the important conversions we made, from lists to arrays, and from array to pd.Seris, and
# vice-versa. Go ahead and give them a try.

In [86]:
# pandas series can hold a variety of data structures
func_list = [sum,len,print]
pd.Series(func_list)

0      <built-in function sum>
1      <built-in function len>
2    <built-in function print>
dtype: object

In [87]:
new_list = [1,'class','name',2.0,'subject',[1,2]]

In [106]:
pd.Series(new_list, index = 'a b c d e f'.split()) # you can save variety of data structures inside an pandas series

a          1
b      class
c       name
d          2
e    subject
f     [1, 2]
dtype: object

## Using An Index:

In [92]:
data = [1,2,3,4]
index = ['USA', 'GERMANY', 'USSR', 'PAKISTAN']

series_1 = pd.Series(data = data, index = index)

In [93]:
series_2 = pd.Series(data = [1,2,5,4], index = ['USA', 'GERMANY', 'ITALY', 'PAKISTAN'])

In [94]:
series_1

USA         1
GERMANY     2
USSR        3
PAKISTAN    4
dtype: int64

In [95]:
series_2

USA         1
GERMANY     2
ITALY       5
PAKISTAN    4
dtype: int64

In [97]:
series_1['USA']  # report back the column value on corresponding index here --> USA

1

In [98]:
series_1['GERMANY']

2

In [101]:
series_2['PAKISTAN']

4

In [102]:
# NOW lets add these two series, series_1, and series_2 to find out the results

In [103]:
series_1 + series_2 # adds the corresponding column values e.g 

GERMANY     4.0
ITALY       NaN
PAKISTAN    8.0
USA         2.0
USSR        NaN
dtype: float64

In [105]:
print(series_1)
print(series_2)

USA         1
GERMANY     2
USSR        3
PAKISTAN    4
dtype: int64
USA         1
GERMANY     2
ITALY       5
PAKISTAN    4
dtype: int64
