In [ ]:
import tensorflow as tf

hello = tf.constant('hello world')
x = tf.constant(100)

session = tf.session()

session.run(hello)
session.run(x)

x = tf.constant(2)
y = tf.constant(3)

with tf.session() as session:
    print('Operations with constants')
    print('Addion', session.run(x+y))
    print('Subtraction', session.run(x-y))
    print('Multiplication', session.run(x*y))
    print('Division', session.run(x/y))
    
# general syntax

# session = session()
# session.run(hello)

# Defining Operations:

add = tf.add(x,y)
sub = tf.sub(x,y)
mul = tf.mul(x,y)

d = {'x':20, 'Y'}

with tf.session() as session:
    print('Operations with Place Holders')
    print('Addition', session.run(add,feed_dict = d))
    print('Multiplication', session.run(mul,feed_dict = d))
    print('Subtraction', session.run(sub, feed_dict = d))

In [16]:
import numpy as np

In [19]:
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [20]:
a

array([[5., 5.]])

In [21]:
type(a)

numpy.ndarray

In [22]:
b

array([[2.],
       [2.]])

In [23]:
type(b)

numpy.ndarray

In [24]:
c = np.array([2,3])

In [25]:
c

array([2, 3])

In [26]:
type(c)

numpy.ndarray

In [28]:
d = np.array([[2,3],[5,6]])

In [29]:
d

array([[2, 3],
       [5, 6]])

In [30]:
a.shape

(1, 2)

In [31]:
type(a.shape)

tuple

In [32]:
b.shape

(2, 1)

In [ ]:
mat_1 = tf.constant(a)
mat_2  = tf.constant(b)

mat_product = tf.matmul(a,b)

with tf.session as session:
    result = session.run(mat_product)
    print(result)