## Tensorflow Syntax Basics:

In [1]:
import tensorflow as tf

In [3]:
# lets check out the version of our tensorflow
print(tf.__version__)

1.14.0


In [12]:
# Word tensor is just a fancy word for 'n-dimentional array'
# let's define some tensors using tensorflow syntax

hello = tf.constant("Hello ")
world = tf.constant("World ")

In [13]:
# now if we want to print these tensors, let's see what we get

print(hello)

# It's not gonna print it as a string, it's rather gonna show some information related to the corresponding tensor

Tensor("Const_4:0", shape=(), dtype=string)


In [14]:
# Let's check out the type of it, to get a bit more clear picture!

type(world)

# reports back that it's a tensor object!

tensorflow.python.framework.ops.Tensor

In [15]:
# Now lets go ahead and create a Tensorflow session, it order to have these tensors work!

with tf.Session() as sess:
    # and we can have block of code that corresponds to the operations we want to perform in tensorflow
    # with tensor objects
    result = sess.run(hello + world)

In [16]:
print(result)

b'Hello World '


In [19]:
# Let's perform another similar type of Example

a = tf.constant(10)
b = tf.constant(20)
print('\n')
print(a)
print(b)
print('\n')
print(a + b)
print('\n')
with tf.Session() as sess:
    result = sess.run(a + b)

print(result)



Tensor("Const_9:0", shape=(), dtype=int32)
Tensor("Const_10:0", shape=(), dtype=int32)


Tensor("add_3:0", shape=(), dtype=int32)


30


Now let's go ahead and create a bunch of basic operations we can perform with Tensorflow

### Constant():

create a Tensorflow constant

In [21]:
const = tf.constant(10)

### Fill():

Fill out the Tensor (fancy word for n-dimentional array) with provided value 'X'

In [23]:
fill_mat = tf.fill((4,4), 10) # (4,4) -> dimentions, (10) -> value to be filled in

### Zeros():

Create a zeros Tensor (n-dimentional array)

In [24]:
zeros = tf.zeros((4,4)) # (4,4) -> dimentions

### Ones():

Creates a One Tensor(n-dimentional matrix)

In [25]:
ones = tf.ones((5,5)) # (5,5) -> dimentions

### random_normal():

Creates a random Tensor with normally distributed values.

In [29]:

randn = tf.random_normal((4,4), mean = 0, stddev = 1) # (4,4) -> shape, mean -> mean, stddev -> standard deviation

### random_uniform():

Creates a random Tensor with uniformly distributed values.

In [30]:
randu = tf.random_uniform((4,4), minval = 0, maxval = 1) # (4,4) -> shape, minval -> minimum value, maxval -> maximum value

None of these operations have been executed up till now.

Let's go ahead and create a list of these operations!

And then we'll run these inside a session!

In [31]:
my_ops = [const, fill_mat, zeros, ones, randn, randu]

### InteractiveSession():

If we use InteractiveSession(), It's going to allow us to call it throughout multiples cells, and we don't have to start the sessoin every single time using 'with' keyword, and basically the rest of the cells are going to kind of pretend that they've already been called from 'with tf.Session()'

So, let's go ahead and create one!

In [33]:
sess = tf.InteractiveSession()

for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 1.0651757   0.80298215 -1.0739136   0.08529232]
 [-0.5517949   0.9912124  -1.0719582  -0.23076953]
 [-0.12018985  1.3075441   1.1031972   0.09825155]
 [-1.173949   -1.2848837   1.5681969  -0.5819555 ]]


[[0.3927815  0.28550804 0.19761574 0.27789497]
 [0.54044366 0.63720524 0.04658639 0.96757543]
 [0.2532357  0.8552934  0.2741543  0.7035191 ]
 [0.12524533 0.86633456 0.7963407  0.18922484]]




/home/umairshah/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


### get_shape():

Reports back the shape of the Tensor(n-dimentional array)!

In [36]:
mat1 = tf.constant([[1,2],
                   [3,4]])

print(mat1.get_shape()) # ()2,2) matrix

(2, 2)


In [37]:
mat2 = tf.constant([[2],
                   [7]])

In [38]:
print(mat2.get_shape())

(2, 1)


### matmul():

Multiplies two matrices, that must have columns of first Matrix equals rows of second Matrix

In [39]:
result = tf.matmul(mat1, mat2)

In [40]:
sess.run(result)

array([[16],
       [34]], dtype=int32)

In [42]:
result.eval() # we can also go ahead and call. eval() method off of result object, to get the results!

array([[16],
       [34]], dtype=int32)